name: Haxe-Tokentree

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
    - cron: '15 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        haxe-version: ['4.0.5', '4.1.4', 'nightly']
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Run npm install
      run: npm ci
    - name: Install Haxe version ${{ matrix.haxe-version }}
      run: |
        npx lix download haxe ${{ matrix.haxe-version }}
        npx lix use haxe ${{ matrix.haxe-version }}
    - name: Run lix download
      run: npx lix download
    - name: Print versions
      run: |
        npx haxe -version
        npx neko -version
        npx haxelib list
    - name: Clone checkstyle
      run: git clone -b dev https://github.com/HaxeCheckstyle/haxe-checkstyle.git --depth=1 checkstyle
    - name: Run npm install for checkstyle
      run: |
        (cd checkstyle; npm install)
    - name: Install Haxe version ${{ matrix.haxe-version }} for checkstyle
      run: |
        (cd checkstyle; npx lix download haxe ${{ matrix.haxe-version }})
        (cd checkstyle; npx lix use haxe ${{ matrix.haxe-version }})
    - name: Run lix download for checkstyle
      run: (cd checkstyle; npx lix download)
    - name: Setup tokentree dev for checkstyle
      run: |
        (cd checkstyle/haxe_libraries; echo "-cp ../src" > tokentree.hxml)
    - name: Run eval tests (without coverage)
      if: matrix.haxe-version == '4.0.5'
      run: npx haxe testWithoutCoverage.hxml
    - name: Run eval tests (with coverage)
      if: matrix.haxe-version != '4.0.5'
      run: npx haxe test.hxml
    - name: Build and test checkstyle
      if: matrix.haxe-version != 'nightly'
      run: (cd checkstyle && npx haxe buildAll.hxml && rm -f coverage.json)
    - name: Run Node version with --check
      if: matrix.haxe-version != 'nightly'
      run: npx neko checkstyle/run.n -s src -s test
    - name: Upload results to codecov
      if: success() && (matrix.haxe-version == '4.1.4')
      run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
